### ISSUE TITLE
Bugs in Toptest output from Eagle

### ISSUE THREAD

**Issue by QrchackOfficial** [nitrocaster/eagleview#1]
I've just managed to build on macOS, testing on several Eagle files I can see a couple of issues:

### [Critical] Board Outline
Board outline points fall outside of the maximums given, causing OpenBoardView to crash right away with no warning due to
```
FileFormats/BRD2File.cpp:85: BRD2File::BRD2File(std::vector<char>&): Assertion `point.y <= max.y` failed.
```
Output:
```
388420
BRDOUT: 9 650 2050
-225 1275
-150 1350
-150 3250
-225 3325
-725 3325
-800 3250
-800 1350
-725 1275
-225 1275
```
3325 falls outside the max of 2050 given. Replacing 2050 -> 3325 using a text editor causes the file to open properly, with the correct board shape.

### Parts
XY coordinates seem to be max/min values with no regard to the actual placement. Starting pin and side are correct. Example output:
```
PARTS: 7
JP1 2147483647 2147483647 -2147483648 -2147483648 0 1
JP3 2147483647 2147483647 -2147483648 -2147483648 10 1
J2 2147483647 2147483647 -2147483648 -2147483648 20 1
J3 2147483647 2147483647 -2147483648 -2147483648 23 1
J4 2147483647 2147483647 -2147483648 -2147483648 26 1
J1 2147483647 2147483647 -2147483648 -2147483648 29 1
JP2 2147483647 2147483647 -2147483648 -2147483648 32 1
```

### Pins
Pins are getting assigned to side 0 (multilayer), which is neither 1 (top side), nor 2 (bottom side) and doesn't get displayed in OpenBV. Output:

```
PINS: 40
-675 3150 1 0
-675 3250 2 0
-575 3150 1 0
-575 3250 2 0
[...]
```

Pins are through hole as seen here:
![image](https://user-images.githubusercontent.com/3584315/123549062-af71b480-d767-11eb-857b-a1efbe440ac1.png)
![image](https://user-images.githubusercontent.com/3584315/123549078-b8fb1c80-d767-11eb-8536-68fd6b299cf6.png)

---

Test file was https://github.com/pichenettes/breadboard-friends/blob/master/bbf-eurojacks.brd
Resaved in Eagle 9.6.1 to convert to the new XML format readable by eagleview.

**Comment by nitrocaster** [comment]
Thanks for your feedback! I believe the test file was bbf-eurojacks.brd, right? I'll have a look and see what can be done.

**Comment by QrchackOfficial** [comment]
> Thanks for your feedback! I believe the test file was bbf-eurojacks.brd, right? I'll have a look and see what can be done.

Yes. I've talked to piernov, and https://github.com/OpenBoardView/OpenBoardView/commit/b89e755a286c404296de6d835211f602819dc381#diff-578500d4d1a7d331e0db862d9cea769bed4124423e1c55a0c1714d1920d2de33 breaks pins that are on both sides. He pushed a fix to OpenBV master already, and also removed the board outline assert that caused it to crash. Outline data is still technically not valid, but at least it will fail silently now.

**Comment by QrchackOfficial** [comment]
Looks like it's maybe an issue with importing pre-6.0 Eagle files, https://github.com/TomWhitwell/TuringMachine exports nicely out of the box

![image](https://user-images.githubusercontent.com/3584315/123554441-49455b80-d780-11eb-81b1-5afd58b8bb26.png)
![image](https://user-images.githubusercontent.com/3584315/123554436-434f7a80-d780-11eb-85bf-dfe11053bd33.png)

**Comment by nitrocaster** [comment]
> Pins are getting assigned to side 0 (multilayer), which is neither 1 (top side), nor 2 (bottom side) and doesn't get displayed in OpenBV

That's actually completely legit. A1312 820-2901-A features through-hole inductors around the CPU, their pins are assigned to side 0, and OBV doesn't display them just as well. In other words, it's a bug in OBV.
```
10594 2519 1 0
12794 3717 1 0
11791 4719 1 0
```
