### ISSUE TITLE
Seems to do incorrect rotation of parts. 

### ISSUE THREAD

**Issue by terriblefire** [nitrocaster/eagleview#2]
When i export an eagle pcb (9.6.2) with parts that have been rotated (270 degree) the toptest board file output looks very wrong. Part are perpendicular to the actual orientation 

Example BRD file in here. 

[tf1230r1_archive (1).zip](https://github.com/nitrocaster/eagleview/files/7254181/tf1230r1_archive.1.zip)

**Comment by terriblefire** [comment]
First thing i noticed is that errno is not cleared before using it in EagleBoard.cpp

[patch.diff.txt](https://github.com/nitrocaster/eagleview/files/7254332/patch.diff.txt)

**Comment by nitrocaster** [comment]
Toptest boardviews do not specify part shapes or rotations. They can be only deduced heuristically.
errno issue is completely valid though. I pushed a fix.
